### ISSUE TITLE
NAtiveAOT: Unable to cast object of type 'MethodPointerValue' to type 'ValueTypeValue

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1005]
When compiling https://github.com/kant2002/CoMallocNativeAot (I change slightly)
Error appears.
```
System.InvalidCastException: Unable to cast object of type 'MethodPointerValue' to type 'ValueTypeValue'.
     at ILCompiler.TypePreinit.FieldAccessor.SetField(FieldDesc field, Value value)
     at ILCompiler.TypePreinit.ByRefValue.ILCompiler.TypePreinit.IHasInstanceFields.SetField(FieldDesc field, Value value)
     at ILCompiler.TypePreinit.TryScanMethod(MethodIL methodIL, Value[] parameters, Stack`1 recursionProtect, Value& returnValue)
     at ILCompiler.TypePreinit.TryScanMethod(MethodDesc method, Value[] parameters, Stack`1 recursionProtect, Value& returnValue)
     at ILCompiler.TypePreinit.TryScanMethod(MethodIL methodIL, Value[] parameters, Stack`1 recursionProtect, Value& returnValue)
     at ILCompiler.TypePreinit.TryScanMethod(MethodDesc method, Value[] parameters, Stack`1 recursionProtect, Value& returnValue)
     at ILCompiler.TypePreinit.TryScanMethod(MethodIL methodIL, Value[] parameters, Stack`1 recursionProtect, Value& returnValue)
     at ILCompiler.TypePreinit.TryScanMethod(MethodDesc method, Value[] parameters, Stack`1 recursionProtect, Value& returnValue)
     at ILCompiler.TypePreinit.TryScanMethod(MethodIL methodIL, Value[] parameters, Stack`1 recursionProtect, Value& returnValue)
     at ILCompiler.TypePreinit.ScanType(CompilationModuleGroup compilationGroup, ILProvider ilProvider, MetadataType type)
     at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey key)
     at ILCompiler.PreinitializationManager.IsPreinitialized(MetadataType type)
     at ILCompiler.PreinitializationManager.HasLazyStaticConstructor(TypeDesc type)
     at ILCompiler.DependencyAnalysis.EETypeNode.ComputeRareFlags(NodeFactory factory, Boolean relocsOnly)
     at ILCompiler.DependencyAnalysis.EETypeNode.ComputeOptionalEETypeFields(NodeFactory factory, Boolean relocsOnly)
     at ILCompiler.DependencyAnalysis.EETypeNode.GetData(NodeFactory factory, Boolean relocsOnly)
     at ILCompiler.DependencyAnalysis.ObjectNode.GetStaticDependencies(NodeFactory factory)
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1 node)
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependencies(DependencyNodeCore`1 node)
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ProcessMarkStack()
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes()
     at ILCompiler.ILScanner.ILCompiler.IILScanner.Scan()
     at ILCompiler.Program.Run(String[] args)
     at ILCompiler.Program.Main(String[] args)
```

`field == {native int._value}`
Method where this is happens is `{native int..ctor(void*)}`

Forget to mention that this is was inside `GetIUnknownImpl(out IntPtr fpQueryInteface, out IntPtr fpAddRef, out IntPtr fpRelease);`.

**Comment by MichalStrehovsky** [comment]
The easiest fix would be to add a check to `FieldAccessor::SetField` along the lines of:

```csharp
if (value is not ValueTypeValue)
    ThrowHelper.ThrowInvalidProgramException();
```

We need that check to protect from invalid IL anyway (e.g. storing a reference type into an IntPtr field). The IL is not strictly invalid in this case, but we don't have a way to express what it's doing so we might as well have it handled by that.

**Comment by kant2002** [comment]
It magically works now in the GitHub build (a.k.a workflows). It's second time this project and maybe stale Nuget give me false positives. Will try to figure out what kind of IL produce this error.

**Comment by jkotas** [comment]
> stale Nuget

You may have a stale -dev package in your nuget cache that takes prececence over the package on the nuget feed.

**Comment by MichalStrehovsky** [comment]
I think you can repro this with something along the lines of (I didn't bother with the exact `delegate*` syntax):

```csharp
class Foo
{
    public IntPtr _ptr;
    static Foo s_foo { get; } = new Foo() { _ptr = (delegate*)&X; }
    static void X() => ...;
}
```

In a static constructor, you need to assign a function pointer into an instance field.
