### ISSUE TITLE
WPF NativeAOT compilation failed

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1106]
I try run blank .NET 6 WPF application via NativeAOT, but compilation fails

```
EXEC : error : Failed to load type 'System.Windows.Freezable' from assembly 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [CoreRTWinFormsTestBed\WpfTestBed\WpfTestBed.csproj]
  Internal.TypeSystem.TypeSystemException+TypeLoadException: Failed to load type 'System.Windows.Freezable' from assembly 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
     at Internal.TypeSystem.ThrowHelper.ThrowTypeLoadException(ExceptionStringID id, String typeName, String assemblyName)
     at Internal.TypeSystem.ResolutionFailure.Throw()
     at Internal.TypeSystem.Ecma.EcmaModule.GetObject(EntityHandle handle, NotFoundBehavior notFoundBehavior)
     at Internal.TypeSystem.Ecma.EcmaModule.GetType(EntityHandle handle)
     at Internal.TypeSystem.Ecma.EcmaType.InitializeBaseType()
     at Internal.TypeSystem.Ecma.EcmaType.ComputeTypeFlags(TypeFlags mask)
     at Internal.TypeSystem.TypeDesc.InitializeTypeFlags(TypeFlags mask)
     at Internal.TypeSystem.TypeSystemContext.GetRuntimeInterfacesAlgorithmForType(TypeDesc type)
     at Internal.TypeSystem.TypeDesc.InitializeRuntimeInterfaces()
     at Internal.TypeSystem.MetadataRuntimeInterfacesAlgorithm.ComputeRuntimeInterfacesForNonInstantiatedMetadataType(MetadataType type)
     at Internal.TypeSystem.TypeDesc.InitializeRuntimeInterfaces()
     at ILCompiler.CompilerTypeSystemContext.EnsureLoadableTypeUncached(TypeDesc type)
     at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey key)
     at ILCompiler.DependencyAnalysis.EETypeNode..ctor(NodeFactory factory, TypeDesc type)
     at ILCompiler.DependencyAnalysis.NodeFactory.CreateNecessaryTypeNode(TypeDesc type)
     at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
     at ILCompiler.DependencyAnalysis.GenericCompositionNode.GetData(NodeFactory factory, Boolean relocsOnly)
     at ILCompiler.DependencyAnalysis.ObjectNode.GetStaticDependencies(NodeFactory factory)
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1 node)
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependencies(DependencyNodeCore`1 node)
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ProcessMarkStack()
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes()
     at ILCompiler.RyuJitCompilation.CompileInternal(String outputFile, ObjectDumper dumper)
     at ILCompiler.Compilation.ILCompiler.ICompilation.Compile(String outputFile, ObjectDumper dumper)
     at ILCompiler.Program.Run(String[] args)
     at ILCompiler.Program.Main(String[] args)
```
ILC response file has 
```
-r:...\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\6.0.0-preview.5.21258.1\framework\WindowsBase.dll
.... skipped
--conditionalroot:...\packages\microsoft.windowsdesktop.app.runtime.win-x64\6.0.0-preview.4.21223.2\runtimes\win-x64\lib\net6.0\System.Windows.Input.Manipulations.dll
```

WindowsBase from `6.0.0-preview.5.21258.1\framework\WindowsBase.dll` has only type references and no actual code, but if I add WindowsBase from `6.0.0-preview.4.21223.2` compilation continue working.

**Comment by jkotas** [comment]
There are two WindowsBase.dlls:
- Minimal one built in dotnet/runtime (https://github.com/dotnet/runtime/blob/main/src/libraries/shims/generated/WindowsBase.csproj)
- Full one one that comes with WPF

The full one is supposed to replace the minumum one whenever WPF is referenced. It is not happening in this case. The minimum one is included in the ILCompiler package and we unconditionally use the .dlls from ILCompiler package whenever there is conflict. It makes sense for .dlls at low levels of the stack such as System.Private.CoreLib, but it does not quite work for .dlls at higher levels of the stack such as System.Private.CoreLib.

I think the problem may be in https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/src/coreclr/tools/aot/ILCompiler.Build.Tasks/ComputeManagedAssembliesToCompileToNative.cs or in how this task is called from https://github.com/dotnet/runtimelab/tree/feature/NativeAOT/src/coreclr/nativeaot/BuildIntegration.

Alternatively, it may be possible to fix this by omitting the minimum WindowsBase.dll in https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/src/installer/pkg/projects/Microsoft.DotNet.ILCompiler/Microsoft.DotNet.ILCompiler.pkgproj

**Comment by Symbai** [comment]
Since when does NativeAOT works with WPF? It has been always said it only works for console or library projects.

**Comment by Fabi** [comment]
> Since when does NativeAOT works with WPF? It has been always said it only works for console or library projects.

Since the COM wrapper commit I guess?

**Comment by Kesanov** [comment]
In the meantime, is there a workaround around this bug?

I am getting the same error with `6.0.0-preview.4.21174.2` and can't resolve `6.0.0-preview.4.21223.2`.

**Comment by kant2002** [comment]
@Josef-Vonasek I manually modify ILC response file to point to proper WindowsBase.dll and then manually run ILC. Then link manually to move forward. 
You will hit #1107 but if you willing to follow advice and hack around, then maybe you can move further then me.

**Comment by Suchiman** [comment]
@Symbai @Fabi @Josef-Vonasek while COM support is one blocker for WPF, a much bigger blocker is that WPF uses C++/CLI which NativeAOT does not support and is very unlikely to ever support (and even if NativeAOT were to reimplement the native API in CoreCLR used by C++/CLI, it wouldn't be possible to statically link these mixed mode assemblies).

**Comment by kant2002** [comment]
WPF is compiled now, so I will move forward with playing on the ComWrappers implementation. I understand that likely I hit mixe dmode assembly, but I want understand where this is happens, maybe simple WPF app will just work, so who want can start hacking around.
