### ISSUE TITLE
Another WPF compiler crash in NativeAOT

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1110]
After I manually pass WindowsBase after 
```
Process terminated. Assertion failed.
   at Internal.TypeSystem.TypeSystemComparer.Compare(MethodDesc x, MethodDesc y) in runtimelab\src\coreclr\tools\Common\TypeSystem\Sorting\TypeSystemComparer.cs:line 86
   at ILCompiler.DependencyAnalysis.MethodExceptionHandlingInfoNode.CompareToImpl(ISortableNode other, CompilerComparer comparer) in runtimelab\src\coreclr\tools\aot\ILCompiler.Compiler\Compiler\DependencyAnalysis\MethodExceptionHandlingInfoNode.cs:line 49
   at ILCompiler.DependencyAnalysis.SortableDependencyNode.ObjectNodeComparer.Compare(DependencyNodeCore`1 x1, DependencyNodeCore`1 y1) in runtimelab\src\coreclr\tools\Common\Compiler\DependencyAnalysis\SortableDependencyNode.cs:line 147
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.Merge(T[] localCopyOfHalfOfArray, TDataStructure arrayToSort, Int32 index, Int32 halfLen, Int32 length, TComparer comparer) in runtimelab\src\coreclr\tools\Common\Sorting\MergeSortCore.cs:line 108
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.MergeSortHelper(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer, T[] scratchSpace) in runtimelab\src\coreclr\tools\Common\Sorting\MergeSortCore.cs:line 84
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.MergeSortHelper(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer, T[] scratchSpace) in runtimelab\src\coreclr\tools\Common\Sorting\MergeSortCore.cs:line 81
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.MergeSortHelper(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer, T[] scratchSpace) in runtimelab\src\coreclr\tools\Common\Sorting\MergeSortCore.cs:line 81
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.MergeSortHelper(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer, T[] scratchSpace) in runtimelab\src\coreclr\tools\Common\Sorting\MergeSortCore.cs:line 82
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.SequentialSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer) in runtimelab\src\coreclr\tools\Common\Sorting\MergeSortCore.cs:line 59
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.ParallelSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer) in runtimelab\src\coreclr\tools\Common\Sorting\MergeSortCore.cs:line 36
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.ParallelSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer)
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.ParallelSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer) in runtimelab\src\coreclr\tools\Common\Sorting\MergeSortCore.cs:line 47
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.ParallelSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer)
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.ParallelSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer) in runtimelab\src\coreclr\tools\Common\Sorting\MergeSortCore.cs:line 47
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.ParallelSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer)
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.ParallelSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer) in runtimelab\src\coreclr\tools\Common\Sorting\MergeSortCore.cs:line 47
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.ParallelSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer)
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.ParallelSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer) in runtimelab\src\coreclr\tools\Common\Sorting\MergeSortCore.cs:line 47
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.ParallelSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer)
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.ParallelSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer) in runtimelab\src\coreclr\tools\Common\Sorting\MergeSortCore.cs:line 47
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.ParallelSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer)
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.ParallelSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer) in runtimelab\src\coreclr\tools\Common\Sorting\MergeSortCore.cs:line 47
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.ParallelSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer)
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.ParallelSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer) in runtimelab\src\coreclr\tools\Common\Sorting\MergeSortCore.cs:line 47
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.ParallelSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer)
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.<>c__DisplayClass2_1.<ParallelSort>b__0() in runtimelab\src\coreclr\tools\Common\Sorting\MergeSortCore.cs:line 43
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

This assertion happens on `{[S.P.CompilerGenerated]Internal.CompilerGenerated.<Module>.CalliMarshallingMethodThunk(native int,native int)}`

Then I have another exception
```
Symbol __ehinfo_Internal_CompilerGenerated__Module___<Calli>UnmanagedCallingConventionCdecl, Static<Int32__IntPtr> has already been written to the output object file obj\Debug\net6.0-windows\win-x64\native\WpfTestBed.obj with symbol ILCompiler.DependencyAnalysis.MethodExceptionHandlingInfoNode
   at ILCompiler.DependencyAnalysis.ObjectWriter.EmitObject(String objectFilePath, IEnumerable`1 nodes, NodeFactory factory, ObjectWritingOptions options, IObjectDumper dumper) in runtimelab\src\coreclr\tools\aot\ILCompiler.Compiler\Compiler\DependencyAnalysis\ObjectWriter.cs:line 994
   at ILCompiler.RyuJitCompilation.CompileInternal(String outputFile, ObjectDumper dumper) in runtimelab\src\coreclr\tools\aot\ILCompiler.RyuJit\Compiler\RyuJitCompilation.cs:line 73
   at ILCompiler.Compilation.ILCompiler.ICompilation.Compile(String outputFile, ObjectDumper dumper) in runtimelab\src\coreclr\tools\aot\ILCompiler.Compiler\Compiler\Compilation.cs:line 491
   at ILCompiler.Program.Run(String[] args)
   at ILCompiler.Program.Main(String[] args)
```

This seems to be related to assertion.

**Comment by jkotas** [comment]
We are missing handling of `EmbeddedSignatureData` in `GetPrefixMangledSignatureName`

**Comment by MichalStrehovsky** [comment]
This is #153.
