### ISSUE TITLE
AOT compilation failed 

### ISSUE THREAD

**Issue by wingrime** [dotnet/runtimelab#1172]
project runs on net5.0 runtime without problem, and have  small portion net 4.8 targeted assemblies. 

```
<PackageReference Include="Microsoft.DotNet.ILCompiler" Version="6.0.0-*" />
used 6.0.0-preview.6.21276.1
```

```
dotnet publish -r win-x64 -c Release
...
C:\Users\shestakovap\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\6.0.0-preview.6.21276.1\framework\System.ComponentModel.TypeConverter.dll : warning IL9702: Assembly 'System.ComponentModel.TypeConverter' produced AOT analysis warnings. [C:\develop\help-portal\src\SkbKontur.Help.Web\SkbKontur.Help.Web.csproj]
C:\Users\shestakovap\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\6.0.0-preview.6.21276.1\framework\System.Linq.Expressions.dll : warning IL9702: Assembly 'System.Linq.Expressions' produced AOT analysis warnings. [C:\develop\help-portal\src\SkbKontur.Help.Web\SkbKontur.Help.Web.csproj]
EXEC : error : Failed to load type 'System.Runtime.Remoting.ObjRef' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' [C:\develop\help-portal\src\SkbKontur.Help.Web\SkbKontur.Help.Web.csproj]
  Internal.TypeSystem.TypeSystemException+TypeLoadException: Failed to load type 'System.Runtime.Remoting.ObjRef' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
     at Internal.TypeSystem.ThrowHelper.ThrowTypeLoadException(ExceptionStringID id, String typeName, String assemblyName)
     at Internal.TypeSystem.ResolutionFailure.Throw()
     at Internal.TypeSystem.Ecma.EcmaModule.GetObject(EntityHandle handle, NotFoundBehavior notFoundBehavior)
     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ResolveHandle(EntityHandle handle)
     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseTypeImpl(SignatureTypeCode typeCode)
     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseType(SignatureTypeCode typeCode)
     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseType()
     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseMethodSignatureImpl(Boolean skipEmbeddedSignatureData)
     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseMethodSignatureInternal(Boolean skipEmbeddedSignatureData)
     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseMethodSignature()
     at Internal.TypeSystem.Ecma.EcmaMethod.InitializeSignature()
     at Internal.TypeSystem.MetadataVirtualMethodAlgorithm.FindMatchingVirtualMethodOnTypeByNameAndSig(MethodDesc targetMethod, DefType currentType, Boolean reverseMethodSearch, Func`3 nameSigMatchMethodIsValidCandidate)
     at Internal.TypeSystem.MetadataVirtualMethodAlgorithm.FindSlotDefiningMethodForVirtualMethod(MethodDesc method)
     at Internal.TypeSystem.MetadataVirtualMethodAlgorithm.EnumAllVirtualSlots(MetadataType type)+MoveNext()
     at ILCompiler.DependencyAnalysis.EETypeNode.GetConditionalStaticDependencies(NodeFactory factory)
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1 node)
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependencies(DependencyNodeCore`1 node)
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ProcessMarkStack()
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes()
     at ILCompiler.ILScanner.ILCompiler.IILScanner.Scan()
     at ILCompiler.Program.Run(String[] args)
     at ILCompiler.Program.Main(String[] args)
C:\Users\shestakovap\.nuget\packages\microsoft.dotnet.ilcompiler\6.0.0-preview.6.21276.1\build\Microsoft.NETCore.Native.targets(282,5): error MSB3073: выход из команды ""C:\Users\shestakovap\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\6.0.0-preview.6.21276.1\tools\ilc" @"obj\Release\net5.0\win-x64\native\SkbKontur.Help.Web.ilc.rsp"" с кодом 1. [C:\develop\help-portal\src\SkbKontur.Help.Web\SkbKontur.Help.Web.csproj]

```

**Comment by MichalStrehovsky** [comment]
NativeAOT compiler doesn't support projects targeting the desktop .NET Framework. An AOT compiler needs to look at everything in the assembly. The JIT-based runtimes have the luxury of only having to look at things that are needed _right now_ so can often sidestep invalid inputs.

The compiler can recover from this sometimes (and generate code that throws at runtime), but it doesn't work in general. Adding more upfront checks so that we can avoid hard crashes slows down the compilation. Upfront checks for virtual method tables would be particularly expensive. There are no plans to fix this, sorry.

**Comment by wingrime** [comment]
Project runs without a problem on net 5.0 on linux alpine. 

Is there way to hint compliler not look into some dependences?
