### ISSUE TITLE
FailFast doesn't fail fast enough

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtimelab#1277]
We hit a segfault when ICU is missing on Linux instead of the helpful FailFast message ("Couldn't find a valid ICU package installed on the system.").

We should probably short-circuit Console.Error and do file writes to stderr directly.

```
Thread 1 "bflat" received signal SIGSEGV, Segmentation fault.
0x0000000001a03895 in System_Console_System_Text_EncodingHelper__GetCharset ()
(gdb) bt
#0  0x0000000001a03895 in System_Console_System_Text_EncodingHelper__GetCharset ()
#1  0x0000000001a037a9 in System_Console_System_Text_EncodingHelper__GetEncodingFromCharset ()
#2  0x00000000019fd729 in System_Console_System_ConsolePal__GetConsoleEncoding ()
#3  0x00000000019fc738 in System_Console_System_Console__get_OutputEncoding ()
#4  0x00000000019fc80b in System_Console_System_Console__CreateOutputWriter ()
#5  0x00000000019fca43 in System_Console_System_Console___get_Error_g__EnsureInitialized_27_0 ()
#6  0x00000000018465b0 in S_P_DeveloperExperience_Console_Internal_Runtime_CompilerHelpers_LibraryInitializer___c___InitializeLibrary_b__0_0 ()
#7  0x0000000001108255 in S_P_CoreLib_System_RuntimeExceptionHelpers__FailFast_1 ()
#8  0x00000000011c354d in S_P_CoreLib_System_Globalization_GlobalizationMode_Settings___cctor ()
#9  0x00000000011b38d9 in S_P_CoreLib_System_Runtime_CompilerServices_ClassConstructorRunner__EnsureClassConstructorRun
    ()
#10 0x00000000011b37e9 in S_P_CoreLib_System_Runtime_CompilerServices_ClassConstructorRunner__CheckStaticClassConstructionReturnNonGCStaticBase ()
#11 0x0000000001149393 in S_P_CoreLib_System_Globalization_CultureData__CreateCultureWithInvariantData ()
#12 0x000000000114945a in S_P_CoreLib_System_Globalization_CultureData__get_Invariant ()
#13 0x000000000115dc5c in S_P_CoreLib_System_Globalization_TextInfo___cctor ()
#14 0x00000000011b38d9 in S_P_CoreLib_System_Runtime_CompilerServices_ClassConstructorRunner__EnsureClassConstructorRun
    ()
#15 0x00000000011b37d9 in S_P_CoreLib_System_Runtime_CompilerServices_ClassConstructorRunner__CheckStaticClassConstructionReturnGCStaticBase ()
#16 0x0000000001a0388e in System_Console_System_Text_EncodingHelper__GetCharset ()
#17 0x0000000001a037a9 in System_Console_System_Text_EncodingHelper__GetEncodingFromCharset ()
#18 0x00000000019fd729 in System_Console_System_ConsolePal__GetConsoleEncoding ()
#19 0x00000000019fc738 in System_Console_System_Console__get_OutputEncoding ()
#20 0x00000000019fc80b in System_Console_System_Console__CreateOutputWriter ()
#21 0x00000000019fc9a3 in System_Console_System_Console___get_Out_g__EnsureInitialized_25_0 ()
#22 0x00000000019fc8e0 in System_Console_System_Console__WriteLine_12 ()
#23 0x00000000017f88b2 in bflat_Program__Run ()
#24 0x00000000017fc572 in bflat_Program__Main ()
#25 0x0000000001dbf225 in bflat__Module___StartupCodeMain ()
#26 0x0000000000dec7ae in main ()
```

**Comment by jkotas** [comment]
> We should probably short-circuit Console.Error and do file writes to stderr directly.

Internal.Console from CoreLib does that.

**Comment by MichalStrehovsky** [comment]
> Internal.Console from CoreLib does that.

To stdout. Might need to add something for stderr.
