### ISSUE TITLE
Question: NativeAOT-LLVM: GVM call logic causing Generics.cs failure?

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1551]
Continues from https://github.com/dotnet/runtimelab/issues/1484#issuecomment-916972227

I have this failure running the Generics.cs test with the lastest head from NativeAOT.  Stack repeated here:

```
exception thrown: RuntimeError: abort(undefined) at Error
    at jsStackTrace (E:\GitHub\runtimelab2\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\Generics\Generics\native\Generics.js:1656:19)
    at stackTrace (E:\GitHub\runtimelab2\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\Generics\Generics\native\Generics.js:1673:16)
    at abort (E:\GitHub\runtimelab2\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\Generics\Generics\native\Generics.js:1389:44)
    at _abort (E:\GitHub\runtimelab2\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\Generics\Generics\native\Generics.js:5807:7)
    at Assert(char const*, char const*, unsigned int, char const*) (wasm-function[19750]:0xdba5f4)
    at RhpNewFinalizableAlign8 (wasm-function[20000]:0xdc7b6e)
    at S_P_CoreLib_System_Runtime_RuntimeExports__RhNewObject (wasm-function[115]:0xce27)
    at S_P_CoreLib_System_Buffers_ArrayPoolEventSource___cctor (wasm-function[3421]:0x1deb78)
    at invoke_vi (E:\GitHub\runtimelab2\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\Generics\Generics\native\Generics.js:7302:25)
    at S_P_CoreLib_System_Runtime_CompilerServices_ClassConstructorRunner__EnsureClassConstructorRun (wasm-function[284]:0x23482)
    at S_P_CoreLib_System_Buffers_TlsOverPerCoreLockedStacksArrayPool_1<Char>__Rent (wasm-function[2449]:0x17f794)
    at S_P_CoreLib_System_Runtime_CompilerServices_DefaultInterpolatedStringHandler___ctor (wasm-function[1122]:0x93b83)
    at Generics_Program_TestGvmDependenciesFromLazy_Bar__Frob<System___Canon> (wasm-function[2633]:0x19419d)
    at Generics_Program_TestGvmDependenciesFromLazy_Foo__FrobToo<System___Canon> (wasm-function[2044]:0x12e21d)
    at Generics_Program_TestGvmDependenciesFromLazy__Run (wasm-function[463]:0x33b34)
```
I've changed the test to 
```
           public virtual string Frob<T>()
            {
                if(typeof(T) == null)
                {
                    Console.WriteLine("typeof null");
                }
                else
                {
                    Console.WriteLine("typeof not null");
                    Console.WriteLine(typeof(T).ToString());
                }
                return $"Foo.Frob<{typeof(T)}>()";
            }
            public virtual string FrobToo<T>()
            {
                if (typeof(T) == null)
                {
                    Console.WriteLine("FrobToo typeof null");
                }
                else
                {
                    Console.WriteLine("FrobToo typeof not null");
                    Console.WriteLine(typeof(T).ToString());
                }
                return Frob<T>();
            }
```
And this prints
```
FrobToo typeof not null
System.Object
undefined
```
Looks like something incorrect is happening in the call to `Frob<>`  .  This call is generated in https://github.com/dotnet/runtimelab/blob/2c0287d7a7a6f51492839938eb0fe0e03d330883/src/coreclr/tools/aot/ILCompiler.LLVM/CodeGen/ILToLLVMImporter.cs#L2582  where it first checks if its a GVM call in https://github.com/dotnet/runtimelab/blob/2c0287d7a7a6f51492839938eb0fe0e03d330883/src/coreclr/tools/aot/ILCompiler.LLVM/CodeGen/ILToLLVMImporter.cs#L2600

Where it builds a call to `__GenericLookupFromDict_Generics_Program_TestGvmDependenciesFromLazy_Foo__FrobToo<System___Canon>_MethodHandle_Generics_Program_TestGvmDependenciesFromLazy_Foo__Frob<T_System___Canon>`
. calls `S_P_CoreLib_System_Runtime_TypeLoaderExports__GVMLookupForSlot` for the context (which is fat at runtime)

I think that looks right, it passes the generic context passed into `FrobToo` to do the method dictionary lookup.

In `Frob<>`  it takes the generic context parameter and passes it to `__GenericLookupFromDict_Generics_Program_TestGvmDependenciesFromLazy_Bar__Frob<System___Canon>_TypeHandle_T_System___Canon`  .  That's right I suppose, i.e. that is a type dictionary because we want the type, not a method handle dictionary like it does in `FrobToo<>` ?
 
The result of that call is passed to `S_P_CoreLib_Internal_Runtime_CompilerHelpers_LdTokenHelpers__GetRuntimeTypeHandle`

I can instrument some more, but @MichalStrehovsky , and insights you might have as to what is different about the `TestGvmDependenciesFromLazy` test (which I think is newish), would be appreciated.  Thanks

**Comment by yowl** [comment]
The method table for IFoo looks like this.  The 2 nulls might be interesting, 
```
@__MethodTable_Generics_Program_TestGvmDependenciesFromLazy_IFoo = global [6 x i32*] 
[
 i32* inttoptr (i32 -1476395008 to i32*), 
 i32* inttoptr (i32 12 to i32*), 
 i32* null, 
 i32* null, 
 i32* inttoptr (i32 34913616 to i32*), 
 i32* bitcast ([2 x i32*]* @__typemanager_indirection to i32*)
]
```
Edit: guess this is fine, those nulls are just the `RelatedTypeUnion` and `_usNumVtableSlots`/`_usNumInterfaces`

**Comment by yowl** [comment]
Or maybe the problem is a lot simpler and my thinking https://github.com/dotnet/runtimelab/blob/2c0287d7a7a6f51492839938eb0fe0e03d330883/src/coreclr/nativeaot/Runtime/portable.cpp#L171 is wrong and this is possible...

**Comment by MichalStrehovsky** [comment]
The implementation of `RhpNewFinalizableAlign8` asserts in source code:

```c++
COOP_PINVOKE_HELPER(Object *, RhpNewFinalizableAlign8, (MethodTable* pEEType))
{
    Object * pObject = nullptr;
    /* Not reachable as finalizable types are never align8 */ ASSERT_UNCONDITIONALLY("UNREACHABLE");
    return pObject;
}
```

Looks like we have some ARM32 assembly helpers that just tailcall to NewObject with `GC_ALLOC_FINALIZE | GC_ALLOC_ALIGN8` and I can also see some code in RhBind (.NET Native) that selects this helper. I think the assert is wrong, it should be implemented.

**Comment by yowl** [comment]
You are right.  I did look in `ArrayPoolEventSource` and didn't immediately see anything that was finalizable and then quickly jumped to the conclusion that it was going to be some hard bug in my LLVM code.
