### ISSUE TITLE
NativeAOT-LLVM: Failure to compile HelloWorld 

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1838]
I try to run `dotnet publish --self-contained -r browser-wasm /p:MSBuildEnableWorkloadResolver=false` on hello world sample. I receive following error
```
  Unhandled exception. System.DllNotFoundException: Unable to load shared library 'clrjit_browser_wasm32_x64' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libclrjit_browser_wasm32_x64: cannot open shared object file: No such file or directory
     at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
     at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
     at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
     at Internal.JitInterface.JitConfigProvider.<>c__DisplayClass5_0.<Initialize>b__0(String libName, Assembly assembly, Nullable`1 searchPath) in ~/runtimelab/src/coreclr/tools/Common/JitInterface/JitConfigProvider.cs:line 55
     at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
     at Internal.JitInterface.CorInfoImpl.jitStartup(IntPtr host)
     at Internal.JitInterface.CorInfoImpl.Startup() in ~/runtimelab/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 162
     at Internal.JitInterface.JitConfigProvider.Initialize(TargetDetails target, IEnumerable`1 jitFlags, IEnumerable`1 parameters, String jitPath) in ~/runtimelab/src/coreclr/tools/Common/JitInterface/JitConfigProvider.cs:line 65
     at ILCompiler.LLVMCodegenCompilationBuilder.ToCompilation() in ~/runtimelab/src/coreclr/tools/aot/ILCompiler.LLVM/Compiler/LLVMCodegenCompilationBuilder.cs:line 92
     at ILCompiler.Program.Run(String[] args) in ~/runtimelab/src/coreclr/tools/aot/ILCompiler/Program.cs:line 792
     at ILCompiler.Program.Main(String[] args) in ~/runtimelab/src/coreclr/tools/aot/ILCompiler/Program.cs:line 967
```

**Comment by yowl** [comment]
The linux build is not working, see #1828.  I assume this is linux due to `~/` in the path

**Comment by kant2002** [comment]
That was caused actually by missing steps for bulding `wasmjit` on Linux. Per our discussion in gitter I was able to start building `wasmjit` on Linux by applying changes in this file https://github.com/dotnet/runtimelab/compare/feature/NativeAOT-LLVM...yowl:llvm-linux#diff-af66f6b851332d1e155eef9bf358246005bd77648b156261a74ef36ee90ea1e9R237

Other Linux build issues related to `PAL_STDCPP_COMPAT` still applied.
