### ISSUE TITLE
NativeAOT-LLVM: heap corruption

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1984]
Hi,

I wonder if anyone can look at this, and maybe give me some more ideas as I've been looking at it for quite a few hours without success, thanks.

If I turn on the `HeapVerifyLevel` setting in `gcconfig.h` to 7 (i.e. all 3 flags), then I can make the verify_heap function fail in node's v8 with this code inserted into `HelloWasm.cs`:

Fails at the third GC.Collect.  Previous to this code, there has been a around a 100 other GC Collects, manual, and automatic that pass the verify checks.
```
GC.Collect();
PrintLine("collect 4");

GC.Collect();
var arrayType = GetArrayType();
PrintLine("collect 4a");
GC.Collect();
```
where `GetArrayType` is 
```
private static Type GetArrayType()
{
    return typeof(object[]);
}
```

Fails with (I have a printf("garbage_collect") in `garbage_collect`)
```
garbage_collect
collect 4
garbage_collect
collect 4a
garbage_collect
E:\GitHub\runtimelab\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\HelloWasm\HelloWasm\native\HelloWasm.js:386
      throw ex;
      ^

RuntimeError: unreachable
    at GCToOSInterface::DebugBreak() (wasm-function[21832]:0xf33c8b)
    at WKS::gc_heap::verify_heap(int) (wasm-function[21191]:0xeada88)
    at WKS::gc_heap::garbage_collect(int) (wasm-function[21108]:0xe7ad2a)
    at WKS::GCHeap::GarbageCollectGeneration(unsigned int, gc_reason) (wasm-function[21105]:0xe79ec3)
    at WKS::GCHeap::GarbageCollectTry(int, int, int) (wasm-function[21487]:0xf117ea)
    at WKS::GCHeap::GarbageCollect(int, bool, int) (wasm-function[21486]:0xf11494)
    at RhpCollect (wasm-function[20100]:0xe0ee7b)
    at S_P_CoreLib_System_Runtime_InternalCalls__RhpCollect (wasm-function[10626]:0x689ecf)
    at S_P_CoreLib_System_Runtime_InternalCalls__RhCollect (wasm-function[7478]:0x4dfc6f)
    at RhCollect (wasm-function[7477]:0x4dfc06)
    at S_P_CoreLib_System_GC__Collect_0 (wasm-function[8161]:0x54580a)
    at HelloWasm_Program__Main (wasm-function[8764]:0x5ab1e3)
    at HelloWasm__Module___MainMethodWrapper (wasm-function[10672]:0x68f395)
    at StartupCodeMain (wasm-function[10664]:0x68ecd7)
    at __managed__Main (wasm-function[20035]:0xe0c408)
    at main (wasm-function[21930]:0xf3b259)
    at E:\GitHub\runtimelab\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\HelloWasm\HelloWasm\native\HelloWasm.js:1747:22
    at callMain (E:\GitHub\runtimelab\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\HelloWasm\HelloWasm\native\HelloWasm.js:7933:15)
    at doRun (E:\GitHub\runtimelab\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\HelloWasm\HelloWasm\native\HelloWasm.js:7990:23)
    at run (E:\GitHub\runtimelab\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\HelloWasm\HelloWasm\native\HelloWasm.js:8005:5)
    at runCaller (E:\GitHub\runtimelab\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\HelloWasm\HelloWasm\native\HelloWasm.js:7911:19)
    at removeRunDependency (E:\GitHub\runtimelab\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\HelloWasm\HelloWasm\native\HelloWasm.js:1669:7)
    at receiveInstance (E:\GitHub\runtimelab\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\HelloWasm\HelloWasm\native\HelloWasm.js:1836:5)
    at receiveInstantiationResult (E:\GitHub\runtimelab\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\HelloWasm\HelloWasm\native\HelloWasm.js:1854:5)
```
If I change `GetArrayType` to
```
private static Type GetArrayType()
{
    return typeof(object);
}
```
Then it passes this point.  So it looks like there might be something funny with `object[]`, although it could be coincidence.  If I look at the method table for `object[]` I see
```
@"__MethodTable___Array<Object>___REALBASE" = global [26 x i32*] 
[
i32* inttoptr (i32 -12 to i32*), 
i32* inttoptr (i32 8 to i32*), 
i32* inttoptr (i32 1 to i32*), 
i32* inttoptr (i32 -1054736380 to i32*),
i32* inttoptr (i32 12 to i32*), 
i32* bitcast ([10 x i32*]* @__MethodTable_Object to i32*), 
i32* inttoptr (i32 720900 to i32*), 
i32* inttoptr (i32 -1744651090 to i32*), 
i32* bitcast (void (i8*, i8*)* @Object__ToString to i32*), 
i32* bitcast (i8 (i8*)* @Object__Equals to i32*),
i32* bitcast (i32 (i8*)* @Object__GetHashCode to i32*), 
i32* bitcast ([4 x i32*]* @"__GenericDict_S_P_CoreLib_System_Array_1<Object>" to i32*), 
i32* bitcast ([6 x i32*]* @__MethodTable_S_P_CoreLib_System_Collections_IEnumerable to i32*), 
i32* bitcast ([7 x i32*]* @__MethodTable_S_P_CoreLib_System_Collections_ICollection to i32*),
i32* bitcast ([8 x i32*]* @__MethodTable_S_P_CoreLib_System_Collections_IList to i32*), 
i32* bitcast ([6 x i32*]* @__MethodTable_S_P_CoreLib_System_Collections_IStructuralComparable to i32*),
i32* bitcast ([6 x i32*]* @__MethodTable_S_P_CoreLib_System_Collections_IStructuralEquatable to i32*), 
i32* bitcast ([6 x i32*]* @__MethodTable_S_P_CoreLib_System_ICloneable to i32*), 
i32* bitcast ([10 x i32*]* @"__MethodTable_S_P_CoreLib_System_Collections_Generic_IEnumerable_1<Object>" to i32*), 
i32* bitcast ([11 x i32*]* @"__MethodTable_S_P_CoreLib_System_Collections_Generic_ICollection_1<Object>" to i32*), 
i32* bitcast ([12 x i32*]* @"__MethodTable_S_P_CoreLib_System_Collections_Generic_IList_1<Object>" to i32*), 
i32* bitcast ([11 x i32*]* @"__MethodTable_S_P_CoreLib_System_Collections_Generic_IReadOnlyCollection_1<Object>" to i32*), 
i32* bitcast ([12 x i32*]* @"__MethodTable_S_P_CoreLib_System_Collections_Generic_IReadOnlyList_1<Object>" to i32*), 
i32* bitcast ([2 x i32*]* @__typemanager_indirection to i32*), i32* bitcast ([2 x i32*]* @"__optionalfields___MethodTable___Array<Object>" to i32*), 
i32* bitcast ([5 x i32*]* @"__SealedVTable___MethodTable___Array<System___Canon>" to i32*)
]
```
Is there anything that sticks out there? I can only see that the last entry is a over `Canon` where as the other generic entries are over `Object`.  Is that ok?

**Comment by jkotas** [comment]
Nothing sticks out here.

What is the exact condition that `verify_heap` fails on?

**Comment by yowl** [comment]
Its this check:
```cpp
// Brick Table Verification...
//
// On brick transition
//     if brick is negative
//          verify that brick indirects to previous valid brick
//     else
//          set current brick invalid flag to be flipped if we
//          encounter an object at the correct place
//
if (curr_brick != prev_brick)
{
// If the last brick we were examining had positive
// entry but we never found the matching object, then
// we have a problem
// If prev_brick was the last one of the segment
// it's ok for it to be invalid because it is never looked at
if (bCurrentBrickInvalid &&
    (curr_brick != brick_of (heap_segment_mem (seg))) &&
    !heap_segment_read_only_p (seg))
{
    printf ("curr brick %lu invalid\n", curr_brick);
    FATAL_GC_ERROR2();
}
```
 Line 42311 in the NativeAOT-LLVM branch of `gc.cpp`  `curr_brick` when it fails is `618`
( I changed the dprintf (haven't looked up what `GC_LOG` does, and the `FATAL..` macro so it wasn't inlined)

**Comment by jkotas** [comment]
This is likely a problem like missing GC write barrier or an object not getting reported to the GC during stackwalk. The way to debug the GC problems like this one is using logs.

**Comment by yowl** [comment]
I dont have a write barrier for `cpobj` https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.cpobj?view=net-6.0  .  Should I?

`initobj` is also missing a write barrier, I suppose if `cpobj` needs it then so does `initobj` .

**Comment by jkotas** [comment]
cpobj needs gc write barrier.

initobj does not need write barrier. The write barrier is not needed when you are storing nulls.

**Comment by yowl** [comment]
> The write barrier is not needed when you are storing nulls.

Of course, doh.

**Comment by yowl** [comment]
I wonder if I've actually gone the other way...too many `RhpAssignRef`s.  For
https://github.com/dotnet/runtimelab/blob/8ac90a4815a96f5470e753960dcc616d007795c6/src/coreclr/tools/Common/Internal/NativeFormat/NativeFormatReader.String.cs#L61
I'm using a `RhpAssignRef` for the `value` assignment, but that's a ref arg, so I wonder if that's messing something up.

```
public unsafe uint DecodeString(uint offset, out string value)
```

**Comment by jkotas** [comment]
> 'm using a RhpAssignRef for the value assignment

This needs to use `RhpCheckedAssignRef`

**Comment by yowl** [comment]
`RhpCheckedAssignRef` doesn't have one of these:
```cs
[RuntimeImport(Redhawk.BaseName, "RhpAssignRef")]
[MethodImpl(MethodImplOptions.InternalCall)]
internal static extern unsafe void RhpAssignRef(ref object address, object obj);
```
I guess I can add it for `TARGET_WASM` ?

**Comment by jkotas** [comment]
> I guess I can add it for TARGET_WASM ?

I think so.

**Comment by yowl** [comment]
I wonder,  in the write barrier
```cs
FORCEINLINE void InlineWriteBarrier(void * dst, void * ref)
{
    if (((uint8_t*)ref >= g_ephemeral_low) && ((uint8_t*)ref < g_ephemeral_high))
    {
        // volatile is used here to prevent fetch of g_card_table from being reordered
        // with g_lowest/highest_address check above. See comment in code:gc_heap::grow_brick_card_tables.
        uint8_t* pCardByte = (uint8_t *)VolatileLoadWithoutBarrier(&g_card_table) + ((size_t)dst >> LOG2_CLUMP_SIZE);
        if (*pCardByte != 0xFF)
            *pCardByte = 0xFF;
    }
}
```
I could add an else that asserts, otherwise is there is other code that uses a stack address here it will be a nop.  I expect there are more instances of this error in the IL backend.

Edit: or maybe not.  I'm not really sure I understand the limits of `g_ephemeral_low` , `g_ephemeral_high` and `g_lowest_address`, `g_highest_address`  .   The ephemeral limits are gen0+gen1 if I understand correctly.  Are they not wholly contained in `g_lowest_address` -> `g_highest_address` ?

**Comment by jkotas** [comment]
> The emphemeral limits are gen0+gen1 if I understand correctly

Correct. They are wholly contained in `g_lowest_address` -> `g_highest_address`.

Also note that the check against `g_ephemeral_low` and `g_ephemeral_high` is done against `ref` (ie the value being assigned).

The assert you have in mind should be done using `g_lowest_address` and `g_highest_address` against `dst` (ie the destination address).

**Comment by yowl** [comment]
oh, yes, thank you.

**Comment by yowl** [comment]
Believe this is one remaining issue to do with the shadow stack arg passed to nested finally/filters/catch blocks from the IL module.

**Comment by yowl** [comment]
THis is old and pretty sure long since fixed.
