### ISSUE TITLE
[NativeAOT-LLVM, WASM] double/float 64, RuntimeError: table index is out of bounds

### ISSUE THREAD

**Issue by Kanawanagasaki** [dotnet/runtimelab#2049]
Hi,
It appears that if you use double type then program will crash with following error:
```
RuntimeError: table index is out of bounds
    at RhpGcAlloc (wasm://wasm/04797806:wasm-function[19138]:0xb6f08b)
    at RhpNewArray (wasm://wasm/04797806:wasm-function[19236]:0xb7001e)
    at S_P_CoreLib_System_Diagnostics_StackTrace__InitializeForCurrentThread (wasm://wasm/04797806:wasm-function[4618]:0x3fe169)
    at S_P_CoreLib_System_Diagnostics_StackTrace___ctor_1 (wasm://wasm/04797806:wasm-function[12269]:0x973f35)
    at S_P_CoreLib_System_Exception__DispatchExLLVM (wasm://wasm/04797806:wasm-function[13820]:0x9cfcef)
    at S_P_CoreLib_System_SR__InternalGetResourceString$CatchFA (wasm://wasm/04797806:wasm-function[5272]:0x4def93)
    at LlvmCatchFunclet (wasm://wasm/04797806:wasm-function[269]:0x359c1)
    at RhpCallCatchFunclet (wasm://wasm/04797806:wasm-function[19923]:0xbadf35)
    at S_P_CoreLib_System_SR__InternalGetResourceString (wasm://wasm/04797806:wasm-function[4958]:0x476dc9)
    at invoke_vii (C:\Users\Kanawanagasaki\Desktop\qwe\bin\Debug\net7.0\browser-wasm\native\qwe.js:5187:29)
```

### Steps to reproduce:
1. `mkdir NativeAOTLLVMTest`
2. `cd NativeAOTLLVMTest`
3. `dotnet new console`
4. `dotnet new nugetconfig`
5. in nuget.config add
```
<add key="dotnet-experimental" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-experimental/nuget/v3/index.json" />
```
6. in NativeAOTLLVMTest.csproj add
```
<ItemGroup>
  <PackageReference Include="Microsoft.DotNet.ILCompiler.LLVM; runtime.win-x64.Microsoft.DotNet.ILCompiler.LLVM" Version="7.0.0-*" />
</ItemGroup>
```
7. change Program.cs to
```cs
Console.WriteLine(1d);
```
8. `dotnet publish -r browser-wasm -c Debug /p:TargetArchitecture=wasm /p:PlatformTarget=AnyCPU /p:MSBuildEnableWorkloadResolver=false --self-contained`
9. `cd .\bin\Debug\net7.0\browser-wasm\native`
10. `node .\NativeAOTLLVMTest.js`

**Comment by jkotas** [comment]
cc @yowl

**Comment by yowl** [comment]
This is the full stack (--stack-trace-limit=100).  Its the DiyFP class, thought this was working with the latest changes, but guess not.  Investigating...
```
   at S_P_CoreLib_System_Attribute__OneOrNull (<anonymous>:wasm-function[4839]:0x4bbe7f)
    at S_P_CoreLib_System_Attribute__GetCustomAttribute (<anonymous>:wasm-function[12237]:0xb629c6)
    at S_P_CoreLib_System_Reflection_CustomAttributeExtensions__GetCustomAttribute (<anonymous>:wasm-function[12329]:0xb686e8)
    at S_P_CoreLib_System_Reflection_CustomAttributeExtensions__GetCustomAttribute_3<System___Canon> (<anonymous>:wasm-function[1544]:0x139d2e)
    at S_P_CoreLib_System_Resources_ManifestBasedResourceGroveler__GetNeutralResourcesLanguage (<anonymous>:wasm-function[5361]:0x5adb3a)
    at S_P_CoreLib_System_Resources_ResourceManager__CommonAssemblyInit (<anonymous>:wasm-function[11478]:0xb2e888)
    at S_P_CoreLib_System_Resources_ResourceManager___ctor_3 (<anonymous>:wasm-function[12751]:0xb7e5e0)
    at S_P_CoreLib_System_SR__get_ResourceManager (<anonymous>:wasm-function[16106]:0xc77395)
    at invoke_vii (E:\tmp\doubletest\bin\Debug\net6.0\browser-wasm\native\doubletest.js:6960:29)
    at S_P_CoreLib_System_SR__InternalGetResourceString (<anonymous>:wasm-function[5308]:0x5969d8)
    at invoke_vii (E:\tmp\doubletest\bin\Debug\net6.0\browser-wasm\native\doubletest.js:6960:29)
    at S_P_CoreLib_System_SR__GetResourceString (<anonymous>:wasm-function[4802]:0x4a80f3)
    at S_P_CoreLib_System_SR__get_Arg_NullReferenceException (<anonymous>:wasm-function[13021]:0xb8e63b)
    at S_P_CoreLib_System_NullReferenceException___ctor (<anonymous>:wasm-function[9432]:0xaaf00a)
    at S_P_CoreLib_Internal_Runtime_CompilerHelpers_ThrowHelpers__ThrowNullReferenceException (<anonymous>:wasm-function[9431]:0xaaef72)
    at corert.throwifnull (<anonymous>:wasm-function[99]:0xe7ba)
    at S_P_CoreLib_System_Number_DiyFp__GetBoundaries (<anonymous>:wasm-function[6531]:0x75f5ed)
    at S_P_CoreLib_System_Number_DiyFp__CreateAndGetBoundaries (<anonymous>:wasm-function[16091]:0xc7650c)
    at S_P_CoreLib_System_Number_Grisu3__TryRunDouble (<anonymous>:wasm-function[4528]:0x40a3cf)
    at S_P_CoreLib_System_Number__FormatDouble_0 (<anonymous>:wasm-function[3541]:0x351926)
    at S_P_CoreLib_System_Number__FormatDouble (<anonymous>:wasm-function[4597]:0x4269e2)
    at Double__ToString_1 (<anonymous>:wasm-function[12557]:0xb7308f)
    at S_P_CoreLib_System_IO_TextWriter__Write_9 (<anonymous>:wasm-function[12707]:0xb7b653)
    at S_P_CoreLib_System_IO_TextWriter__WriteLine_10 (<anonymous>:wasm-function[12738]:0xb7d6b7)
    at S_P_CoreLib_System_IO_TextWriter_SyncTextWriter__WriteLine_11 (<anonymous>:wasm-function[4566]:0x41f199)
    at System_Console_System_Console__WriteLine_5 (<anonymous>:wasm-function[13024]:0xb8e911)
    at doubletest_Program___Main__ (<anonymous>:wasm-function[13118]:0xb92c4a)
    at doubletest__Module___MainMethodWrapper (<anonymous>:wasm-function[13838]:0xbb817b)
    at StartupCodeMain (<anonymous>:wasm-function[4317]:0x3e75a4)
    at __managed__Main (<anonymous>:wasm-function[9373]:0xaac4b3)
    at main (<anonymous>:wasm-function[21877]:0xf08e43)
    at E:\tmp\doubletest\bin\Debug\net6.0\browser-wasm\native\doubletest.js:983:22
    at callMain (E:\tmp\doubletest\bin\Debug\net6.0\browser-wasm\native\doubletest.js:7780:15)
    at doRun (E:\tmp\doubletest\bin\Debug\net6.0\browser-wasm\native\doubletest.js:7834:23)
    at run (E:\tmp\doubletest\bin\Debug\net6.0\browser-wasm\native\doubletest.js:7849:5)
    at runCaller (E:\tmp\doubletest\bin\Debug\net6.0\browser-wasm\native\doubletest.js:7757:19)
    at removeRunDependency (E:\tmp\doubletest\bin\Debug\net6.0\browser-wasm\native\doubletest.js:904:7)
    at receiveInstance (E:\tmp\doubletest\bin\Debug\net6.0\browser-wasm\native\doubletest.js:1071:5)
    at receiveInstantiationResult (E:\tmp\doubletest\bin\Debug\net6.0\browser-wasm\native\doubletest.js:1089:5)
```

**Comment by yowl** [comment]
@SingleAccretion, this is happening because we have a difference of opinion about whether `DiyFp` https://github.com/dotnet/runtimelab/blob/feature/NativeAOT-LLVM/src/libraries/System.Private.CoreLib/src/System/Number.DiyFp.cs can live on the LLVM stack.  The IL module thinks it can, but the clrjit module thinks it can't because it has `CORINFO_FLG_CONTAINS_STACK_PTR` and we have 

https://github.com/dotnet/runtimelab/blob/3b24124c8e6aab49a59b629b2d28de74b29c7f94/src/coreclr/jit/llvm.cpp#L540-L548

It contains the fields
```cs
public readonly ulong f;
public readonly int e;
```
 `CORINFO_FLG_CONTAINS_STACK_PTR` is set because it is `metadataType.IsByRefLike` (Note that this is renamed to `CORINFO_FLG_BYREF_LIKE` upstream)

I don't understand why a `ref struct` which lives on the "stack" and has no gc pointers inside has to live on the shadowstack.  Should we be changing `return (classAttribs & (CORINFO_FLG_CONTAINS_GC_PTR | CORINFO_FLG_CONTAINS_STACK_PTR)) == 0;` and dropping `CORINFO_FLG_CONTAINS_STACK_PTR` ?

Thanks

**Comment by SingleAccretion** [comment]
> I don't understand why a ref struct which lives on the "stack" and has no gc pointers inside has to live on the shadowstack.

Right, it doesn't need to.

>  Should we be changing return `(classAttribs & (CORINFO_FLG_CONTAINS_GC_PTR | CORINFO_FLG_CONTAINS_STACK_PTR)) == 0`; and dropping `CORINFO_FLG_CONTAINS_STACK_PTR`?

The problem is that `CORINFO_FLG_CONTAINS_GC_PTR` doesn't tell us about whether we have byref fields. It seems a fine solution to let this be based on `ClassLayout::HasGCPtr` instead.

**Comment by yowl** [comment]
Thanks @Kanawanagasaki  for the report, this should be fixed by the above PR .

**Comment by Kanawanagasaki** [comment]
No problem @yowl
Fixed now 👍
