### ISSUE TITLE
NativeAOT-LLVM: code generation error with (delegate*<void>) ?

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2252]
The move to using `(delegate*<void>)` in 
https://github.com/dotnet/runtime/blob/476bce3456006245bdade1fc38a1a300b10f91e8/src/coreclr/nativeaot/Common/src/Internal/Runtime/CompilerHelpers/StartupCodeHelpers.cs#L171-L186

seems to be causing the code generation to do something strange.  At runtime this fails with 
```
RuntimeError: invalid index into function table
    at S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__RunInitializers (<anonymous>:wasm-function[4064]:0x16c05b)
    at S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules (<anonymous>:wasm-function[4059]:0x16a633)
    at InitializeRuntime() (<anonymous>:wasm-function[17129]:0x11f49af)
    at main (<anonymous>:wasm-function[17128]:0x11f48ba)
    at E:\GitHub\runtimelab3\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\FrameworkStrings\Baseline\native\Baseline.js:986:22
    at callMain (E:\GitHub\runtimelab3\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\FrameworkStrings\Baseline\native\Baseline.js:7260:15)
    at doRun (E:\GitHub\runtimelab3\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\FrameworkStrings\Baseline\native\Baseline.js:7314:23)
    at run (E:\GitHub\runtimelab3\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\FrameworkStrings\Baseline\native\Baseline.js:7329:5)
    at runCaller (E:\GitHub\runtimelab3\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\FrameworkStrings\Baseline\native\Baseline.js:7237:19)
    at removeRunDependency (E:\GitHub\runtimelab3\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\FrameworkStrings\Baseline\native\Baseline.js:907:7)
    at receiveInstance (E:\GitHub\runtimelab3\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\FrameworkStrings\Baseline\native\Baseline.js:1074:5)
    at receiveInstantiationResult (E:\GitHub\runtimelab3\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\FrameworkStrings\Baseline\native\Baseline.js:1092:5)
```
Possibly due to the fact that function pointers in wasm are indices into a table and not actual function pointers.  In the debugger you see

![image](https://user-images.githubusercontent.com/2720041/231205442-daba4450-ec6d-456d-9c69-f193f070adf6.png)

`initializer` looks big for a function index.  Dump attached, but have not looked further than this.

[RunInitializers.zip](https://github.com/dotnet/runtimelab/files/11201859/RunInitializers.zip)

**Comment by yowl** [comment]
My initial thought was the pointer arithmetic, but I don't think that holds water as it fails on the first iteration through the for loop when you'd think no arithmetic would have been performed yet.

**Comment by yowl** [comment]
Thinking is this is an upstream bug and the code should be
```
var initializer = MethodTable.SupportsRelativePointers ? (delegate*<void>)ReadRelPtr32(pCurrent) : *(delegate*<void>*)pCurrent;
```
I'll mention this in the merge PR and maybe you want me to create a PR in runtime.

**Comment by jkotas** [comment]
Yes, this is upstream bug. It would be great if you can create a PR in dotnet/runtime.

**Comment by yowl** [comment]
ok, will do.
