### ISSUE TITLE
browser-wasm - System.TypeLoadException: Could not load type 'System.Runtime.InteropServices.MemoryMarshal'

### ISSUE THREAD

**Issue by oudi** [dotnet/runtimelab#2731]
With the sample https://github.com/dotnet/runtimelab/tree/feature/NativeAOT-LLVM/samples/NativeLibrary

* dotnet --info `Version:      9.0.0-rc.2.24473.5`
* emsdk Version 3.1.70

when click `=` Button in the sample, the console of brower show error below

```
Unhandled exception. System.TypeLoadException: Could not load type 'System.Runtime.InteropServices.MemoryMarshal' from assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKey=002400000480000094000000060200000024000052534131000400000100010007d1fa57c4aed9f0a32e84aa0faefd0de9e8fd6aec8f87fb03766c834c99921eb23be79ad9d5dcc1dd9ad236132102900b723cf980957fc4e177108fc607774f29e8320e92ea05ece4e821c0a5efe8f1645c4c0c93c1ab99285d622caa652c1dfad63d745d6f2de5f17e5eaf0fc4963d261c8a12436518206dc093344d5ad293'.

   at Internal.Runtime.CompilerHelpers.ThrowHelpers.ThrowTypeLoadException(ExceptionStringID, String, String):0x138874
   at NativeLibrary.NativeLibrary.ComputeArithmeticExpression(Byte*):0x19e3e6
   at http://localhost:6931/bin/Release/net9.0/browser-wasm/publish/NativeLibrary.js:594:12
   at HTMLDivElement.<anonymous> (http://localhost:6931/NativeLibraryHost.html:56:34)
Aborted(native code called abort())

Uncaught RuntimeError: Aborted(native code called abort())
    at abort (NativeLibrary.js:561:11)
    at __abort_js (NativeLibrary.js:3874:7)
    at NativeLibrary.wasm:0x1a6cee
    at NativeLibrary.wasm:0x135e40
    at NativeLibrary.wasm:0x149ddc
    at NativeLibrary.wasm:0x19dcd6
    at NativeLibrary.wasm:0x18d8ab
    at NativeLibrary.wasm:0x19e403
    at NativeLibrary.wasm:0x168467
    at NativeLibrary.wasm:0x16828a
```

* NativeLibrary.csproj

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>library</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <PublishTrimmed>true</PublishTrimmed>
    <SelfContained>true</SelfContained>
    <MSBuildEnableWorkloadResolver>false</MSBuildEnableWorkloadResolver>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.ILCompiler.LLVM" Version="9.0.0-*" />
    <PackageReference Include="runtime.$(NETCoreSdkPortableRuntimeIdentifier).Microsoft.DotNet.ILCompiler.LLVM" Version="9.0.0-*" />
  </ItemGroup>

  <ItemGroup>
    <LinkerArg Include="-sEXPORTED_RUNTIME_METHODS=stringToNewUTF8" />
  </ItemGroup>

</Project>
```

* nuget.config

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="dotnet9" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json" />
    <add key="dotnet-public" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json" />
    <add key="dotnet-experimental" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-experimental/nuget/v3/index.json" />
 </packageSources>
</configuration>
```

**Comment by jkotas** [comment]
> Could not load type 'System.Runtime.InteropServices.MemoryMarshal'

This error is caused by breaking changes done between previews and release candidates. It should get fixed by https://github.com/dotnet/runtimelab/pull/2730

**Comment by jkotas** [comment]
Actually, we have the fix in NativeAOT-LLVM branch but it is in 10.0.0 package. Could you please try updating the package versions to 10.0.0 to see whether it fixes it?
```
    <PackageReference Include="Microsoft.DotNet.ILCompiler.LLVM" Version="9.0.0-*" />
    <PackageReference Include="runtime.$(NETCoreSdkPortableRuntimeIdentifier).Microsoft.DotNet.ILCompiler.LLVM" Version="9.0.0-*" />
```

**Comment by oudi** [comment]
> Actually, we have the fix in NativeAOT-LLVM branch but it is in 10.0.0 package. Could you please try updating the package versions to 10.0.0 to see whether it fixes it?
> 
> ```
>     <PackageReference Include="Microsoft.DotNet.ILCompiler.LLVM" Version="9.0.0-*" />
>     <PackageReference Include="runtime.$(NETCoreSdkPortableRuntimeIdentifier).Microsoft.DotNet.ILCompiler.LLVM" Version="9.0.0-*" />
> ```

It fiexed! thanks.

**Comment by jkotas** [comment]
We should update the sample to point to use dotnet10 TFM

**Comment by oudi** [comment]
> We should update the sample to point to use dotnet10 TFM

there are another problem  `stringToNewUTF8` not export! I create a pull to fix this all.
