### ISSUE TITLE
In the multi-byte target code page, there is no character to which this Unicode character can be mapped.(在多字节的目标代码页中，没有此 Unicode 字符可以映射到的字符。)

### ISSUE THREAD

**Issue by 2505817596** [dotnet/runtimelab#479]
Excuse me, I am using dotnet publish -r win-x64 -c release command to prompt the following information, what should I do?

System.IO.IOException: Fail to initialize Native Object Writer
     at ILCompiler.DependencyAnalysis.ObjectWriter..ctor(String objectFilePath, NodeFactory factory)
     at ILCompiler.DependencyAnalysis.ObjectWriter.EmitObject(String objectFilePath, IEnumerable`1 nodes, NodeFactory factory, IObjectDumper dumper)
     at ILCompiler.RyuJitCompilation.CompileInternal(String outputFile, ObjectDumper dumper)
     at ILCompiler.Compilation.ILCompiler.ICompilation.Compile(String outputFile, ObjectDumper dumper)
     at ILCompiler.Program.Run(String[] args)
     at ILCompiler.Program.Main(String[] args)

**Comment by jkotas** [comment]
What is the OS that you are running on? Do you all pre-requisities installed https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/samples/prerequisites.md ?
