### ISSUE TITLE
Error message in building NativeAOT

### ISSUE THREAD

**Issue by acaly** [dotnet/runtimelab#542]
While trying to build the NativeAOT branch following [this instruction](https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/workflow/building/coreclr/nativeaot.md#building), I got error saying:

```
E:\Temp\runtime-nativeaot\runtimelab\eng\illink.targets(215,11): error MSB4057: The target "GetBinPlaceTargetFramework" does not exist in the project. E:\Temp\runtime-nativeaot\runtimelab\eng\illink.targets
```
which points to [this line](https://github.com/dotnet/runtimelab/blob/23ceb0a10cc40771bf6039e9e22abbb60207098c/eng/illink.targets#L215). I cannot find any information in the repo about "GetBinPlaceTargetFramework". Did I miss something?

I also tried removing that line, and the build goes farther, but stops while "Trimming shared framework assemblies with ILLinker", saying

```
  Fatal error in IL Linker
  Unhandled exception. Mono.Linker.InternalErrorException: Unresolved exported type is never marked
     at Mono.Linker.Steps.SweepStep.AssemblyReferencesCorrector.UpdateTypeScope(Collection`1 forwarders)
     at Mono.Linker.Steps.SweepStep.AssemblyReferencesCorrector.Process()
     at Mono.Linker.Steps.SweepStep.SweepAssemblyReferences(AssemblyDefinition assembly)
     at Mono.Linker.Steps.SweepStep.SweepAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.SweepStep.Process()
     at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
```

I am building on Windows 10 with lastest VS.

**Comment by acaly** [comment]
Solved by adding
```
<PropertyGroup>
    <ILLinkTrimAssembly>false</ILLinkTrimAssembly>
</PropertyGroup>
```
in `src\coreclr\tools\Directory.Build.props`.
