### ISSUE TITLE
Unable to cast object of type 'Internal.TypeSystem.ArrayType' to type 'Internal.TypeSystem.Ecma.EcmaType'

### ISSUE THREAD

**Issue by atodkar** [dotnet/runtimelab#550]
I am trying to build Asp.Net core Web Api application as Native-AOT and facing below exception.

EXEC : error : Unable to cast object of type 'Internal.TypeSystem.ArrayType' to type 'Internal.TypeSystem.Ecma.EcmaType'. 

  System.InvalidCastException: Unable to cast object of type 'Internal.TypeSystem.ArrayType' to type 'Internal.TypeSystem.Ecma.EcmaType'.
     at ILCompiler.Dataflow.DynamicallyAccessedMembersBinder.GetPropertiesOnTypeHierarchy(TypeDesc type, Func`2 filter, BindingFlags bindingFlags)+MoveNext()
     at ILCompiler.Dataflow.DynamicallyAccessedMembersBinder.GetDynamicallyAccessedMembers(TypeDesc typeDefinition, DynamicallyAccessedMemberTypes memberTypes)+MoveNext()
     at ILCompiler.Dataflow.ReflectionMethodBodyScanner.MarkTypeForDynamicallyAccessedMembers(ReflectionPatternContext& reflectionContext, TypeDesc typeDefinition, DynamicallyAccessedMemberTypes requiredMemberTypes)
     at ILCompiler.Dataflow.ReflectionMethodBodyScanner.RequireDynamicallyAccessedMembers(ReflectionPatternContext& reflectionContext, DynamicallyAccessedMemberTypes requiredMemberTypes, ValueNode value, Origin targetContext)
     at ILCompiler.Dataflow.ReflectionMethodBodyScanner.ProcessGenericArgumentDataFlow(NodeFactory factory, FlowAnnotations flowAnnotations, Logger logger, GenericParameterDesc genericParameter, TypeDesc genericArgument, TypeSystemEntity source)
     at ILCompiler.UsageBasedMetadataManager.GetFlowDependenciesForInstantiation(DependencyList& dependencies, NodeFactory factory, Instantiation instantiation, Instantiation typicalInstantiation, TypeSystemEntity source)
     at ILCompiler.UsageBasedMetadataManager.GetDependenciesForGenericDictionary(DependencyList& dependencies, NodeFactory factory, MethodDesc method)
     at ILCompiler.DependencyAnalysis.MethodGenericDictionaryNode.ComputeNonRelocationBasedDependencies(NodeFactory factory)
     at ILCompiler.DependencyAnalysis.ObjectNode.GetStaticDependencies(NodeFactory factory)
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1 node)
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ProcessMarkStack()
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes()
     at ILCompiler.ILScanner.ILCompiler.IILScanner.Scan()
     at ILCompiler.Program.Run(String[] args)
     at ILCompiler.Program.Main(String[] args)

Below is my code-

    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseServiceProviderFactory(new AutofacServiceProviderFactory())
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }

**Comment by atodkar** [comment]
ILCompiler version-

<PackageReference Include="Microsoft.DotNet.ILCompiler" Version="6.0.0-alpha.1.21054.2" />

**Comment by MichalStrehovsky** [comment]
Thanks for reporting this. Fixed in #552. The NuGet package with the fix should be out within 24 hours or so.

**Comment by atodkar** [comment]
Appreciated, thank you.
