### ISSUE TITLE
CodeGenerationFailedException using Protobuf.Net

### ISSUE THREAD

**Issue by proficien1t444** [dotnet/runtimelab#578]
Hi!
1) Install protobuf.net
2) Create a simple data class and serialize it 
3) Try to compile it using native aot

` Unhandled exception. ILCompiler.CodeGenerationFailedException: Code generation failed for method 'uint8[]..ctor(int32)'
   ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
     at Internal.IL.Stubs.ArrayMethodILEmitter.EmitIL()
     at Internal.IL.Stubs.ArrayMethodILEmitter.EmitIL(ArrayMethod arrayMethod)
     at Internal.IL.CoreRTILProvider.GetMethodIL(MethodDesc method)
     at ILCompiler.RemovingILProvider.GetMethodIL(MethodDesc method)
     at ILCompiler.FeatureSwitchManager.GetMethodIL(MethodDesc method)
     at ILCompiler.Compilation.CombinedILProvider.GetMethodIL(MethodDesc method)
     at ILCompiler.Compilation.ILCache.CreateValueFromKey(MethodDesc key)
     at Internal.TypeSystem.LockFreeReaderHashtable'2.CreateValueAndEnsureValueIsInTable(TKey key)
     at ILCompiler.Compilation.GetMethodIL(MethodDesc method)
     at Internal.IL.ILImporter..ctor(ILScanner compilation, MethodDesc method, MethodIL methodIL)
     at ILCompiler.ILScanner.CompileSingleMethod(ScannedMethodNode methodCodeNodeNeedingCode)
     --- End of inner exception stack trace ---
     at ILCompiler.ILScanner.CompileSingleMethod(ScannedMethodNode methodCodeNodeNeedingCode)
     at ILCompiler.ILScanner.<CompileMultiThreaded>b__5_0(Object m)
     at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
     at System.Threading.ThreadPoolWorkQueue.Dispatch()
     at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()`

**Comment by jkotas** [comment]
@MichalStrehovsky Does this ctor need to be handled in the ILScanner?

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky Does this ctor need to be handled in the ILScanner?

Yeah, looks like it. I'll take a look.

I don't know what Protobuf is doing there, but I don't really want to know.

Fun fact: there's 0 occurrences of `[]::.ctor` in the entire CoreCLR runtime test tree. I'll fix that one too...

**Comment by MichalStrehovsky** [comment]
Fixed in #586. A new NuGet package should be out within 24 hours or so.

**Comment by proficien1t444** [comment]
@MichalStrehovsky i don't know how many time need to ship  updated nuget package but for 6.0.0-preview.2.21077.2 which is the newest version i have the same error.

**Comment by MichalStrehovsky** [comment]
#602 should be the fix. I blindly fixed another issue that would manifest itself with this stack trace.

This time I actually set up protobuf to see what's going on.
