### ISSUE TITLE
[Native-AOT] Bad diagnostics with no-runtime

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#614]
1. Create application with custom runtime
2. Specify NoSTDlib and friends, but forget to include `IlcSystemModule`
3. Run `dotnet publish`
```
  Generating native code
EXEC : error : Object reference not set to an instance of an object. [D:\d\kant\GitHub\nativeaot-commandline\nativeaot-commandline.csproj]
  System.NullReferenceException: Object reference not set to an instance of an object.
     at ILCompiler.DependencyAnalysis.ObjectNode.GetStaticDependencies(NodeFactory factory)
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1 node)
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes()
     at ILCompiler.RyuJitCompilation.CompileInternal(String outputFile, ObjectDumper dumper)
     at ILCompiler.Compilation.ILCompiler.ICompilation.Compile(String outputFile, ObjectDumper dumper)
     at ILCompiler.Program.Run(String[] args)
     at ILCompiler.Program.Main(String[] args)
```

Would be good to change diagnostic message for that case.

**Comment by kant2002** [comment]
I would close this one. I use older version of package, and current error slightly different and slightly less obscure.
