### ISSUE TITLE
[TEMPORARY EXCEPTION MESSAGE] ClassLoadGeneral: System.Runtime.CompilerServices.CallConvStdcall

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#626]
When compile Shared Native Library 

```
[UnmanagedCallersOnly(EntryPoint = "Initialize", CallConvs = new Type[] { typeof(CallConvStdcall) })]
public static int Initialize(int value)
{
   return -1;
}
```

Receive exception
```
EXEC : error : [TEMPORARY EXCEPTION MESSAGE] ClassLoadGeneral: System.Runtime.CompilerServices.CallConvStdcall, System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a 

  Internal.TypeSystem.TypeSystemException+TypeLoadException: [TEMPORARY EXCEPTION MESSAGE] ClassLoadGeneral: System.Runtime.CompilerServices.CallConvStdcall, System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
     at Internal.TypeSystem.ThrowHelper.ThrowTypeLoadException(ExceptionStringID id, String typeName, String assemblyName)
     at Internal.TypeSystem.Ecma.EcmaModule.GetType(String nameSpace, String name, Boolean throwIfNotFound)
     at Internal.TypeSystem.CustomAttributeTypeNameParser.ResolveCustomAttributeTypeDefinitionName(String name, ModuleDesc module, Boolean throwIfNotFound)
     at Internal.TypeSystem.CustomAttributeTypeNameParser.GetTypeByCustomAttributeTypeName(ModuleDesc module, String name, Boolean throwIfNotFound, Func`4 resolver)
     at System.Reflection.Metadata.Ecma335.CustomAttributeDecoder`1.DecodeArgument(BlobReader& valueReader, ArgumentTypeInfo info)
     at System.Reflection.Metadata.Ecma335.CustomAttributeDecoder`1.DecodeArrayArgument(BlobReader& blobReader, ArgumentTypeInfo info)
     at System.Reflection.Metadata.Ecma335.CustomAttributeDecoder`1.DecodeArgument(BlobReader& valueReader, ArgumentTypeInfo info)
     at System.Reflection.Metadata.Ecma335.CustomAttributeDecoder`1.DecodeNamedArguments(BlobReader& valueReader)
     at System.Reflection.Metadata.Ecma335.CustomAttributeDecoder`1.DecodeValue(EntityHandle constructor, BlobHandle value)
     at System.Reflection.Metadata.CustomAttribute.DecodeValue[TType](ICustomAttributeTypeProvider`1 provider)
     at Internal.TypeSystem.Ecma.MetadataExtensions.GetDecodedCustomAttribute(EcmaMethod This, String attributeNamespace, String attributeName)
     at ILCompiler.MethodExtensions.GetUnmanagedCallersOnlyExportName(EcmaMethod This)
     at ILCompiler.ExportedMethodsRootProvider.AddCompilationRoots(IRootingServiceProvider rootProvider)
     at ILCompiler.Compilation..ctor(DependencyAnalyzerBase`1 dependencyGraph, NodeFactory nodeFactory, IEnumerable`1 compilationRoots, ILProvider ilProvider, DebugInformationProvider debugInformationProvider, DevirtualizationManager devirtualizationManager, Logger logger)
     at ILCompiler.ILScannerBuilder.ToILScanner()
     at ILCompiler.Program.Run(String[] args)
     at ILCompiler.Program.Main(String[] args)
```

**Comment by kant2002** [comment]
Was using wrong version of `Microsoft.DotNet.ILCompiler`. Should use 6.x
