### ISSUE TITLE
ClassLoadGeneral: System.Net.Security.SslClientHelloInfo

### ISSUE THREAD

**Issue by heppth** [dotnet/runtimelab#682]
Hi I am trying to compile an asp.net core 5 application natively. For this I use Microsoft.DotNet.ILCompiler Version="1.0.0-alpha-29408-02". Target platform is linux-x64

I get the following exception: 
```
/usr/bin/clang
8>  Generating compatible native code. To optimize for size or speed, visit https://aka.ms/OptimizeCoreRT
8>EXEC : error : [TEMPORARY EXCEPTION MESSAGE] ClassLoadGeneral: System.Net.Security.SslClientHelloInfo, System.Net.Security, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a [/src/Awesome.Server/Awesome.Server.csproj]
8>  Internal.TypeSystem.TypeSystemException+TypeLoadException: [TEMPORARY EXCEPTION MESSAGE] ClassLoadGeneral: System.Net.Security.SslClientHelloInfo, System.Net.Security, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
8>     at Internal.TypeSystem.ThrowHelper.ThrowTypeLoadException(ExceptionStringID id, String typeName, String assemblyName)
8>     at Internal.TypeSystem.Ecma.EcmaModule.GetType(String nameSpace, String name, Boolean throwIfNotFound)
8>     at Internal.TypeSystem.Ecma.EcmaModule.ResolveTypeReference(TypeReferenceHandle handle)
8>     at Internal.TypeSystem.Ecma.EcmaModule.EcmaObjectLookupHashtable.CreateValueFromKey(EntityHandle handle)
8>     at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey key)
8>     at Internal.TypeSystem.Ecma.EcmaModule.GetObject(EntityHandle handle)
8>     at Internal.TypeSystem.Ecma.EcmaModule.GetType(EntityHandle handle)
8>     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseType(SignatureTypeCode typeCode)
8>     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseMethodSignature()
8>     at Internal.TypeSystem.Ecma.EcmaMethod.InitializeSignature()
8>     at ILCompiler.DependencyAnalysis.MethodMetadataNode.GetStaticDependencies(NodeFactory factory)
8>     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1 node)
8>     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ProcessMarkStack()
8>     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes()
8>     at ILCompiler.ILScanner.ILCompiler.IILScanner.Scan()
8>     at ILCompiler.Program.Run(String[] args)
8>     at ILCompiler.Program.Main(String[] args)
```

I already tried adding System.Security as TrimmerRootAssembly without success
```
  <ItemGroup>
    <TrimmerRootAssembly Include="System.Security" />
  </ItemGroup>
```
Any ideas?

**Comment by MichalStrehovsky** [comment]
> Microsoft.DotNet.ILCompiler Version="1.0.0-alpha-29408-02"

This is an old package published from the archived CoreRT repo. Please switch to the new 6.0 packages first: https://github.com/dotnet/runtimelab/tree/feature/NativeAOT/samples/HelloWorld
